language: python
python:
- '2.7'
sudo: required
before_install:
- sudo apt-get install -y python-lxml libxml2-dev libxslt1-dev git tidy wget
- pip install --use-mirrors pillow cssutils lxml docutils roman
- pip install --use-mirrors future requests
- wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
- tar xvfz kindlegen_linux_2.6_i386_v2_9.tar.gz
- sudo ln -s /kindlegen /usr/local/bin/kindlegen
install:
- pip install git+git://github.com/gitenberg-dev/pg-epubmaker.git
before_script:
- export PATH=$PATH:/usr/local/bin
script:
- python test.py
- epubmaker --ebook=928 --title="Alice's Adventures in Wonderland" --make=all  928-h/928-h.htm
- ls *
- mv 928-epub.epub  Alice-s-Adventures-in-Wonderland-HTML-Edition.epub
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Py1oKQpO0qjNUu3tl/zN1aBWiQ+vZpfMbSIneXZg3ObQ1xhVKZ3P5fFZK/xmCRGrbmjD40lDUaDJle0WWH7kGHovN5flHIW9uiyxTmyPga1QQ6AlcWPmD8tL0GMi9bSwkK38WD6O575Y19t/gOA7LHHW6XgFix6l9F/J78ZqsN+W5NQadAK8V5ILD7Z1cx9lkWO/1qPUQro5MZzWtlbZlD13lSAEslUTdC06qjyO1gDz75vJCSyDA8WSjztlnaGrXRZ4aK9pWYn5NKIxNDZVOZeeLqtOJFjKD1u00O151my9K9+z17ayhQG/vRKYMhgza75BrwTvcnclAkuRPFTnuDud6XpmmS1THM8DWPn1Zy2dXaYwH4YYKJOPGys/K99wQDl2eyNtFck0afrlfzANtNGX003OVL4gR/m3VgCXgwiyizxHRtD9iSDaKHrKhiozYCLjBnyxJZkp4lXgSPDXsNiNzkCPO+ufRnJwHVJlT2KpHNYb2p0XGru8aV913xBNDg8DZSLvh+cVyKB1aJulQ+nRD9Sid6WkUfx8iepc5T4nYW0GblTBl12bItT4PF1ovt6rCoECDjDeVTwK1XXmt0UYO8ZmqjSbVNU9CkRpZ1ogXhax0gUuQj1pLa/RfFQ6t3AcxpOjaxQPssh0JT8jV05Z65TPNKUjueXsadm7mGQ=
  file: Alice-s-Adventures-in-Wonderland-HTML-Edition.epub
  on:
    repo: GITenberg/Alice-s-Adventures-in-Wonderland-HTML-Edition_928
